mod map2many;
pub use map2many::*;
mod map2one;
pub use map2one::*;
mod map3one;
pub use map3one::*;
mod map3many;
pub use map3many::*;
mod map2static;
pub use map2static::*;
mod map3static;
pub use map3static::*;
mod ndeep;
pub use ndeep::*;
mod reshape3to2;
pub use reshape3to2::*;
