[package]
name = "mli-relu"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2024"

[dependencies]
mli = { path = "../mli", version = "0.11.0" }
float-ord = "0.3.2"
nalgebra = { version = "0.33.2", default-features = false }
