[package]
name = "mli-ndarray"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2024"

[dependencies]
mli = { path = "../mli", version = "0.11.0" }
ndarray = "0.16.1"
itertools = "0.14.0"
num-traits = "0.2.19"
ordered-float = "5.0.0"
